all: myshell myshell_extracredit

myshell: myshell.c
	gcc myshell.c -o myshell -Wall
myshell_extracredit: myshell_extracredit.c
	gcc myshell_extracredit.c -o myshell_extracredit -Wall

clean:
	rm myshell myshell_extracredit
