all: copyit copyit_extracredit

copyit: copyit.c
	gcc copyit.c -o copyit -Wall

copyit_extracredit: copyit_extracredit.c
	gcc copyit_extracredit.c -o copyit_extracredit -Wall

clean: 
	rm -f copyit copyit_extracredit

